### ISSUE TITLE
Please ensure that this works with latexmk

### ISSUE THREAD

**Issue by henryso** [kalrish/luatex-lua-module-cache-manager#3]
In various experiments, I've noticed that, for this initialization script to work with latexmk, it needs to allow LuaTeX to emit (or it needs to itself emit) the banner which looks like

```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238)  (format=lualatex 2016.2.17)  20 FEB 2016 14:36
```

as the very first line.  Otherwise latexmk will complain that the log file is not in the right format and will not work properly.

The way it works now, it will emit messages about registering the callback and loading the cache before LuaTeX emits the banner, and latexmk will fail to recognize the log as valid.

**Comment by kalrish** [comment]
I can't reproduce the problem. latexmk 4.43a never complains for me, and the first line of all my log files (in all my projects that use the cache manager) is always the banner. The thing is, the log file isn't yet open at the initialization script stage, and the banner should be the first thing outputted when it is opened. Are you sure latexmk is looking at the log file and not stdout/stderr?

That said, I have already worked on two solutions:
- turn off `info` messages by default
  
  Enable them with a command-line switch.
- output `info` messages only to the log file
  
  They will still be useful without cluttering the terminal. There seem to be many packages in the LaTeX world that take this approach. While it indeed seems the 'smart' one to take, it won't be a good solution if it gives problems with latexmk, so I would like to know where it's looking at.

**Comment by henryso** [comment]
I should have been clearer in the description, and I made it more confusing by mixing up the current script with the results of my experimentation.  As it is and as you say, the script has no problem with latexmk.

What I'm trying to say is that, whatever the fix for #2 ends up being, it should ensure that the first line of the log file is the banner.  When experimenting with registering the load from the cache file to the start_run callback so that it works when multiple passes are necessary (i.e., through latexmk), this prevents the banner from showing up.

**Comment by kalrish** [comment]
Ahh, ok. Don't worry. And thank you! I'll definitely take this into account. I had already played with the `start_run` callback, as you suggested, but hadn't seriously thought about the problems that removing the banner would raise.

I am still considering what to do about #2, though. For now, I have opened a bug report.

**Comment by kalrish** [comment]
It has turned out that the issue with the recorder feature (#2) was due to a bug in LuaTeX. It is therefore unnecessary to load the cache from any callback, so there shouldn't be any problem with latexmk.

That said, if we wanted to add an alternative loading path to support those not running on the fixed version, we would likely be interested in `tex.luatexbanner` (§ 7.14.2, _Convert commands_) and `status.list().banner` (§ 7.13, _The `status` library_). They both seem to hold the same banner issued by LuaTeX, in my limited experimentation, so it should be a matter of:

```
local function polite_cache_loading_callback()
    texio.write( tex.luatexbanner , "\n" )

    -- load the cache
end

callback.register( "start_run" , polite_cache_loading_callback )
```
